export enum Query {
  Alias = 'alias',
  Signatures = 'signatures',
  SetTextSignatures = 'set-text-signatures',
  SetCardSignatures = 'set-card-signatures',
  GetMessageInfoAndContent = 'get_message_info_and_content',
  GetMessageEncryptionKeyState = 'get_message_encryption_key_state',
  GetMessageOnChainIdentifier = 'get_message_on_chain_identifier',
  Sent = 'sent',
  GetSubscribeStatus = 'get_subscribe_status',
  SetSubscribeStatus = 'set_subscribe_status',
  SubscribeProfileInit = 'subscribe profile init',
  SubscriptionArticleInit = 'subscription article init',
  SubscriptionDetail = 'subscription article detai',
  GetUserInfo = 'get_user_info',
  GetCheckPremiumMember = 'check_premium_member',
  GetLanguageCode = 'getLanguageCode',
}
