export enum ErrorCode {
  DUPLICATED_COMMUNITY_SUBSCRIPTION_CAMPAIGN_URL = 'DUPLICATED_COMMUNITY_SUBSCRIPTION_CAMPAIGN_URL',
  INVALID_COMMUNITY_SUBSCRIPTION_CAMPAIGN_URL = 'INVALID_COMMUNITY_SUBSCRIPTION_CAMPAIGN_URL',
  INVALID_COMMUNITY_SUBSCRIPTION_CREDENTIAL = 'INVALID_COMMUNITY_SUBSCRIPTION_CREDENTIAL',
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  ADDRESS_NOT_FOUND = 'ADDRESS_NOT_FOUND',
  COMMUNITY_ADDRESS_NOT_IN_WHITELIST = 'COMMUNITY_ADDRESS_NOT_IN_WHITELIST',
  DOT_BIT_ACCOUNT_NOT_OPENED = 'DOT_BIT_ACCOUNT_NOT_OPENED',
  DOT_BIT_ACCOUNT_NOT_SET_LOWEST_PRICE = 'DOT_BIT_ACCOUNT_NOT_SET_LOWEST_PRICE',
  ADDRESS_INVALID = 'ADDRESS_INVALID',
  COMMUNITY_COLLABORATORS_ADDRESS_INVALID = 'COMMUNITY_COLLABORATORS_ADDRESS_INVALID',
  NOT_OWNED_THE_DOT_BIT_ACCOUNT = 'NOT_OWNED_THE_DOT_BIT_ACCOUNT',
}
