export enum ErrorCode {
  DUPLICATED_COMMUNITY_SUBSCRIPTION_CAMPAIGN_URL = 'DUPLICATED_COMMUNITY_SUBSCRIPTION_CAMPAIGN_URL',
  INVALID_COMMUNITY_SUBSCRIPTION_CAMPAIGN_URL = 'INVALID_COMMUNITY_SUBSCRIPTION_CAMPAIGN_URL',
  INVALID_COMMUNITY_SUBSCRIPTION_CREDENTIAL = 'INVALID_COMMUNITY_SUBSCRIPTION_CREDENTIAL',
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  ADDRESS_NOT_FOUND = 'ADDRESS_NOT_FOUND',
  COMMUNITY_ADDRESS_NOT_IN_WHITELIST = 'COMMUNITY_ADDRESS_NOT_IN_WHITELIST',
}
