export enum ErrorCode {
  DUPLICATED_COMMUNITY_SUBSCRIPTION_CAMPAIGN_URL = 'DUPLICATED_COMMUNITY_SUBSCRIPTION_CAMPAIGN_URL',
  INVALID_COMMUNITY_SUBSCRIPTION_CAMPAIGN_URL = 'INVALID_COMMUNITY_SUBSCRIPTION_CAMPAIGN_URL',
  INVALID_COMMUNITY_SUBSCRIPTION_CREDENTIAL = 'INVALID_COMMUNITY_SUBSCRIPTION_CREDENTIAL',
}
