export enum RoutePath {
  Home = '/',
  Inbox = '/',
  Sent = '/messages/sent',
  Drafts = '/messages/drafts',
  Trash = '/messages/trash',
  Settings = '/settings/address',
  SettingSignature = '/settings/signature',
  Setup = '/setup/address',
  SetupSignature = '/setup/signature',
  SetupShare = '/setup/share',
  NewMessage = '/message/edit',
  WhiteList = '/whitelist',
  Subscription = '/subscription',
  Message = '/message',
  Testing = '/testing',
}
